import os
import distutils.util

import hideout

#
# NOTE: Deprecated. Please use HIDEOUT_CACHE_DIR
# Base directory for storing cache files generated by hideout.
#
HIDEOUT_BASE_DIR = os.getenv('HIDEOUT_BASEDIR', './caches')


def set_cache_dir():
    if HIDEOUT_BASE_DIR != './caches':
        hideout.log.logger.warn("HIDEOUT_BASEDIR is deprecated. Please use HIDEOUT_CACHE_DIR")
        return HIDEOUT_BASE_DIR
    return os.getenv('HIDEOUT_CACHE_DIR', './caches')


#
# Base directory for storing cache files generated by hideout.
#
HIDEOUT_CACHE_DIR = set_cache_dir()

#
# List of stages to skip caching.
#
HIDEOUT_SKIP_STAGES = set(os.getenv('HIDEOUT_SKIP_STAGES', "").split(","))

#
# When this value is set to True, hideout does store / load cache files.
#
# NOTE: https://qiita.com/koemu/items/fd333fd8ed14f31fbca6
#
HIDEOUT_ENABLE_CACHE = bool(distutils.util.strtobool(
    os.getenv('HIDEOUT_ENABLE_CACHE', "False")))
