import os
import distutils.util

#
# Base directory for storing cache files generated by hideout.
#
HIDEOUT_BASEDIR = os.getenv('HIDEOUT_BASEDIR', './')

#
# List of stages to skip caching.
#
HIDEOUT_SKIP_STAGES = os.getenv('HIDEOUT_SKIP_STAGES', '').split(",")

#
# When this value is set to False, hideout does not store / load cache files.
#
# NOTE: https://qiita.com/koemu/items/fd333fd8ed14f31fbca6
HIDEOUT_SUPPRESS_CACHE = bool(distutils.util.strtobool(
    os.getenv('HIDEOUT_SUPPRESS_CACHE', "False")))
